// This file is automatically generated. Any manual edits here will be overwritten on the next update.
package cmd

var resourceToEndpoint = map[string]map[string]string{

	"cloudflare_account": {
		"list": "/accounts",
		"get":  "/accounts/{account_id}",
	},
	"cloudflare_account_member": {
		"list": "/accounts/{account_id}/members",
		"get":  "/accounts/{account_id}/members/{member_id}",
	},
	"cloudflare_account_subscription": {
		"list": "",
		"get":  "/accounts/{account_id}/subscriptions",
	},
	"cloudflare_account_token": {
		"list": "/accounts/{account_id}/tokens",
		"get":  "/accounts/{account_id}/tokens/{token_id}",
	},
	"cloudflare_origin_ca_certificate": {
		"list": "/certificates",
		"get":  "/certificates/{certificate_id}",
	},
	"cloudflare_user": {
		"list": "",
		"get":  "/user",
	},
	"cloudflare_api_token": {
		"list": "/user/tokens",
		"get":  "/user/tokens/{token_id}",
	},
	"cloudflare_zone": {
		"list": "/zones",
		"get":  "/zones/{zone_id}",
	},
	"cloudflare_zone_setting": {
		"list": "",
		"get":  "/zones/{zone_id}/settings/{setting_id}",
	},
	"cloudflare_zone_hold": {
		"list": "",
		"get":  "/zones/{zone_id}/hold",
	},
	"cloudflare_zone_subscription": {
		"list": "",
		"get":  "/zones/{identifier}/subscription",
	},
	"cloudflare_load_balancer": {
		"list": "/zones/{zone_id}/load_balancers",
		"get":  "/zones/{zone_id}/load_balancers/{load_balancer_id}",
	},
	"cloudflare_load_balancer_monitor": {
		"list": "/accounts/{account_id}/load_balancers/monitors",
		"get":  "/accounts/{account_id}/load_balancers/monitors/{monitor_id}",
	},
	"cloudflare_load_balancer_pool": {
		"list": "/accounts/{account_id}/load_balancers/pools",
		"get":  "/accounts/{account_id}/load_balancers/pools/{pool_id}",
	},
	"cloudflare_zone_cache_reserve": {
		"list": "",
		"get":  "/zones/{zone_id}/cache/cache_reserve",
	},
	"cloudflare_tiered_cache": {
		"list": "",
		"get":  "/zones/{zone_id}/cache/tiered_cache_smart_topology_enable",
	},
	"cloudflare_zone_cache_variants": {
		"list": "",
		"get":  "/zones/{zone_id}/cache/variants",
	},
	"cloudflare_regional_tiered_cache": {
		"list": "",
		"get":  "/zones/{zone_id}/cache/regional_tiered_cache",
	},
	"cloudflare_certificate_pack": {
		"list": "/zones/{zone_id}/ssl/certificate_packs",
		"get":  "/zones/{zone_id}/ssl/certificate_packs/{certificate_pack_id}",
	},
	"cloudflare_total_tls": {
		"list": "",
		"get":  "/zones/{zone_id}/acm/total_tls",
	},
	"cloudflare_argo_smart_routing": {
		"list": "",
		"get":  "/zones/{zone_id}/argo/smart_routing",
	},
	"cloudflare_argo_tiered_caching": {
		"list": "",
		"get":  "/zones/{zone_id}/argo/tiered_caching",
	},
	"cloudflare_custom_ssl": {
		"list": "/zones/{zone_id}/custom_certificates",
		"get":  "/zones/{zone_id}/custom_certificates/{custom_certificate_id}",
	},
	"cloudflare_custom_hostname": {
		"list": "/zones/{zone_id}/custom_hostnames",
		"get":  "/zones/{zone_id}/custom_hostnames/{custom_hostname_id}",
	},
	"cloudflare_custom_hostname_fallback_origin": {
		"list": "",
		"get":  "/zones/{zone_id}/custom_hostnames/fallback_origin",
	},
	"cloudflare_dns_firewall": {
		"list": "/accounts/{account_id}/dns_firewall",
		"get":  "/accounts/{account_id}/dns_firewall/{dns_firewall_id}",
	},
	"cloudflare_zone_dnssec": {
		"list": "",
		"get":  "/zones/{zone_id}/dnssec",
	},
	"cloudflare_dns_record": {
		"list": "/zones/{zone_id}/dns_records",
		"get":  "/zones/{zone_id}/dns_records/{dns_record_id}",
	},
	"cloudflare_zone_dns_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/dns_settings",
	},
	"cloudflare_account_dns_settings": {
		"list": "",
		"get":  "/accounts/{account_id}/dns_settings",
	},
	"cloudflare_account_dns_settings_internal_view": {
		"list": "/accounts/{account_id}/dns_settings/views",
		"get":  "/accounts/{account_id}/dns_settings/views/{view_id}",
	},
	"cloudflare_dns_zone_transfers_incoming": {
		"list": "",
		"get":  "/zones/{zone_id}/secondary_dns/incoming",
	},
	"cloudflare_dns_zone_transfers_outgoing": {
		"list": "",
		"get":  "/zones/{zone_id}/secondary_dns/outgoing",
	},
	"cloudflare_dns_zone_transfers_acl": {
		"list": "/accounts/{account_id}/secondary_dns/acls",
		"get":  "/accounts/{account_id}/secondary_dns/acls/{acl_id}",
	},
	"cloudflare_dns_zone_transfers_peer": {
		"list": "/accounts/{account_id}/secondary_dns/peers",
		"get":  "/accounts/{account_id}/secondary_dns/peers/{peer_id}",
	},
	"cloudflare_dns_zone_transfers_tsig": {
		"list": "/accounts/{account_id}/secondary_dns/tsigs",
		"get":  "/accounts/{account_id}/secondary_dns/tsigs/{tsig_id}",
	},
	"cloudflare_email_security_block_sender": {
		"list": "/accounts/{account_id}/email-security/settings/block_senders",
		"get":  "/accounts/{account_id}/email-security/settings/block_senders/{pattern_id}",
	},
	"cloudflare_email_security_impersonation_registry": {
		"list": "/accounts/{account_id}/email-security/settings/impersonation_registry",
		"get":  "/accounts/{account_id}/email-security/settings/impersonation_registry/{display_name_id}",
	},
	"cloudflare_email_security_trusted_domains": {
		"list": "/accounts/{account_id}/email-security/settings/trusted_domains",
		"get":  "/accounts/{account_id}/email-security/settings/trusted_domains/{trusted_domain_id}",
	},
	"cloudflare_email_routing_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/email/routing",
	},
	"cloudflare_email_routing_dns": {
		"list": "",
		"get":  "/zones/{zone_id}/email/routing/dns",
	},
	"cloudflare_email_routing_rule": {
		"list": "/zones/{zone_id}/email/routing/rules",
		"get":  "/zones/{zone_id}/email/routing/rules/{rule_identifier}",
	},
	"cloudflare_email_routing_catch_all": {
		"list": "",
		"get":  "/zones/{zone_id}/email/routing/rules/catch_all",
	},
	"cloudflare_email_routing_address": {
		"list": "/accounts/{account_id}/email/routing/addresses",
		"get":  "/accounts/{account_id}/email/routing/addresses/{destination_address_identifier}",
	},
	"cloudflare_filter": {
		"list": "/zones/{zone_id}/filters",
		"get":  "/zones/{zone_id}/filters/{filter_id}",
	},
	"cloudflare_zone_lockdown": {
		"list": "/zones/{zone_id}/firewall/lockdowns",
		"get":  "/zones/{zone_id}/firewall/lockdowns/{lock_downs_id}",
	},
	"cloudflare_access_rule": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/firewall/access_rules/rules",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/firewall/access_rules/rules/{rule_id}",
	},
	"cloudflare_user_agent_blocking_rule": {
		"list": "/zones/{zone_id}/firewall/ua_rules",
		"get":  "/zones/{zone_id}/firewall/ua_rules/{ua_rule_id}",
	},
	"cloudflare_healthcheck": {
		"list": "/zones/{zone_id}/healthchecks",
		"get":  "/zones/{zone_id}/healthchecks/{healthcheck_id}",
	},
	"cloudflare_keyless_certificate": {
		"list": "/zones/{zone_id}/keyless_certificates",
		"get":  "/zones/{zone_id}/keyless_certificates/{keyless_certificate_id}",
	},
	"cloudflare_logpush_job": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/logpush/jobs",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/logpush/jobs/{job_id}",
	},
	"cloudflare_logpush_ownership_challenge": {
		"list": "",
		"get":  "",
	},
	"cloudflare_logpull_retention": {
		"list": "",
		"get":  "/zones/{zone_id}/logs/control/retention/flag",
	},
	"cloudflare_authenticated_origin_pulls_certificate": {
		"list": "/zones/{zone_id}/origin_tls_client_auth",
		"get":  "/zones/{zone_id}/origin_tls_client_auth/{certificate_id}",
	},
	"cloudflare_authenticated_origin_pulls": {
		"list": "",
		"get":  "/zones/{zone_id}/origin_tls_client_auth/hostnames/{hostname}",
	},
	"cloudflare_authenticated_origin_pulls_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/origin_tls_client_auth/settings",
	},
	"cloudflare_page_rule": {
		"list": "/zones/{zone_id}/pagerules",
		"get":  "/zones/{zone_id}/pagerules/{pagerule_id}",
	},
	"cloudflare_rate_limit": {
		"list": "/zones/{zone_id}/rate_limits",
		"get":  "/zones/{zone_id}/rate_limits/{rate_limit_id}",
	},
	"cloudflare_waiting_room": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/waiting_rooms",
		"get":  "/zones/{zone_id}/waiting_rooms/{waiting_room_id}",
	},
	"cloudflare_waiting_room_event": {
		"list": "/zones/{zone_id}/waiting_rooms/{waiting_room_id}/events",
		"get":  "/zones/{zone_id}/waiting_rooms/{waiting_room_id}/events/{event_id}",
	},
	"cloudflare_waiting_room_rules": {
		"list": "",
		"get":  "/zones/{zone_id}/waiting_rooms/{waiting_room_id}/rules",
	},
	"cloudflare_waiting_room_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/waiting_rooms/settings",
	},
	"cloudflare_web3_hostname": {
		"list": "/zones/{zone_id}/web3/hostnames",
		"get":  "/zones/{zone_id}/web3/hostnames/{identifier}",
	},
	"cloudflare_workers_route": {
		"list": "/zones/{zone_id}/workers/routes",
		"get":  "/zones/{zone_id}/workers/routes/{route_id}",
	},
	"cloudflare_workers_script_subdomain": {
		"list": "",
		"get":  "/accounts/{account_id}/workers/scripts/{script_name}/subdomain",
	},
	"cloudflare_workers_cron_trigger": {
		"list": "",
		"get":  "/accounts/{account_id}/workers/scripts/{script_name}/schedules",
	},
	"cloudflare_workers_deployment": {
		"list": "",
		"get":  "/accounts/{account_id}/workers/scripts/{script_name}/deployments",
	},
	"cloudflare_workers_custom_domain": {
		"list": "/accounts/{account_id}/workers/domains",
		"get":  "/accounts/{account_id}/workers/domains/{domain_id}",
	},
	"cloudflare_workers_kv_namespace": {
		"list": "/accounts/{account_id}/storage/kv/namespaces",
		"get":  "/accounts/{account_id}/storage/kv/namespaces/{namespace_id}",
	},
	"cloudflare_workers_kv": {
		"list": "",
		"get":  "/accounts/{account_id}/storage/kv/namespaces/{namespace_id}/values/{key_name}",
	},
	"cloudflare_queue": {
		"list": "/accounts/{account_id}/queues",
		"get":  "/accounts/{account_id}/queues/{queue_id}",
	},
	"cloudflare_queue_consumer": {
		"list": "",
		"get":  "/accounts/{account_id}/queues/{queue_id}/consumers",
	},
	"cloudflare_api_shield": {
		"list": "",
		"get":  "/zones/{zone_id}/api_gateway/configuration",
	},
	"cloudflare_api_shield_discovery_operation": {
		"list": "/zones/{zone_id}/api_gateway/discovery/operations",
		"get":  "/zones/{zone_id}/api_gateway/discovery/operations",
	},
	"cloudflare_api_shield_operation": {
		"list": "/zones/{zone_id}/api_gateway/operations",
		"get":  "/zones/{zone_id}/api_gateway/operations/{operation_id}",
	},
	"cloudflare_api_shield_operation_schema_validation_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/api_gateway/operations/{operation_id}/schema_validation",
	},
	"cloudflare_api_shield_schema_validation_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/api_gateway/settings/schema_validation",
	},
	"cloudflare_api_shield_schema": {
		"list": "/zones/{zone_id}/api_gateway/user_schemas",
		"get":  "/zones/{zone_id}/api_gateway/user_schemas/{schema_id}",
	},
	"cloudflare_managed_transforms": {
		"list": "/zones/{zone_id}/managed_headers",
		"get":  "/zones/{zone_id}/managed_headers",
	},
	"cloudflare_page_shield_policy": {
		"list": "/zones/{zone_id}/page_shield/policies",
		"get":  "/zones/{zone_id}/page_shield/policies/{policy_id}",
	},
	"cloudflare_ruleset": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/rulesets",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/rulesets/{ruleset_id}",
	},
	"cloudflare_url_normalization_settings": {
		"list": "",
		"get":  "/zones/{zone_id}/url_normalization",
	},
	"cloudflare_spectrum_application": {
		"list": "/zones/{zone_id}/spectrum/apps",
		"get":  "/zones/{zone_id}/spectrum/apps/{app_id}",
	},
	"cloudflare_regional_hostname": {
		"list": "/zones/{zone_id}/addressing/regional_hostnames",
		"get":  "/zones/{zone_id}/addressing/regional_hostnames/{hostname}",
	},
	"cloudflare_address_map": {
		"list": "/accounts/{account_id}/addressing/address_maps",
		"get":  "/accounts/{account_id}/addressing/address_maps/{address_map_id}",
	},
	"cloudflare_byo_ip_prefix": {
		"list": "/accounts/{account_id}/addressing/prefixes",
		"get":  "/accounts/{account_id}/addressing/prefixes/{prefix_id}",
	},
	"cloudflare_image": {
		"list": "/accounts/{account_id}/images/v1",
		"get":  "/accounts/{account_id}/images/v1/{image_id}",
	},
	"cloudflare_image_variant": {
		"list": "/accounts/{account_id}/images/v1/variants",
		"get":  "/accounts/{account_id}/images/v1/variants/{variant_id}",
	},
	"cloudflare_magic_wan_gre_tunnel": {
		"list": "/accounts/{account_id}/magic/gre_tunnels",
		"get":  "/accounts/{account_id}/magic/gre_tunnels/{gre_tunnel_id}",
	},
	"cloudflare_magic_wan_ipsec_tunnel": {
		"list": "/accounts/{account_id}/magic/ipsec_tunnels",
		"get":  "/accounts/{account_id}/magic/ipsec_tunnels/{ipsec_tunnel_id}",
	},
	"cloudflare_magic_wan_static_route": {
		"list": "/accounts/{account_id}/magic/routes",
		"get":  "/accounts/{account_id}/magic/routes/{route_id}",
	},
	"cloudflare_magic_transit_site": {
		"list": "/accounts/{account_id}/magic/sites",
		"get":  "/accounts/{account_id}/magic/sites/{site_id}",
	},
	"cloudflare_magic_transit_site_acl": {
		"list": "/accounts/{account_id}/magic/sites/{site_id}/acls",
		"get":  "/accounts/{account_id}/magic/sites/{site_id}/acls/{acl_id}",
	},
	"cloudflare_magic_transit_site_lan": {
		"list": "/accounts/{account_id}/magic/sites/{site_id}/lans",
		"get":  "/accounts/{account_id}/magic/sites/{site_id}/lans/{lan_id}",
	},
	"cloudflare_magic_transit_site_wan": {
		"list": "/accounts/{account_id}/magic/sites/{site_id}/wans",
		"get":  "/accounts/{account_id}/magic/sites/{site_id}/wans/{wan_id}",
	},
	"cloudflare_magic_transit_connector": {
		"list": "/accounts/{account_id}/magic/connectors",
		"get":  "/accounts/{account_id}/magic/connectors/{connector_id}",
	},
	"cloudflare_magic_network_monitoring_configuration": {
		"list": "",
		"get":  "/accounts/{account_id}/mnm/config",
	},
	"cloudflare_magic_network_monitoring_rule": {
		"list": "/accounts/{account_id}/mnm/rules",
		"get":  "/accounts/{account_id}/mnm/rules/{rule_id}",
	},
	"cloudflare_mtls_certificate": {
		"list": "/accounts/{account_id}/mtls_certificates",
		"get":  "/accounts/{account_id}/mtls_certificates/{mtls_certificate_id}",
	},
	"cloudflare_pages_project": {
		"list": "/accounts/{account_id}/pages/projects",
		"get":  "/accounts/{account_id}/pages/projects/{project_name}",
	},
	"cloudflare_pages_domain": {
		"list": "/accounts/{account_id}/pages/projects/{project_name}/domains",
		"get":  "/accounts/{account_id}/pages/projects/{project_name}/domains/{domain_name}",
	},
	"cloudflare_registrar_domain": {
		"list": "/accounts/{account_id}/registrar/domains",
		"get":  "/accounts/{account_id}/registrar/domains/{domain_name}",
	},
	"cloudflare_list": {
		"list": "/accounts/{account_id}/rules/lists",
		"get":  "/accounts/{account_id}/rules/lists/{list_id}",
	},
	"cloudflare_list_item": {
		"list": "/accounts/{account_id}/rules/lists/{list_id}/items",
		"get":  "/accounts/{account_identifier}/rules/lists/{list_id}/items/{item_id}",
	},
	"cloudflare_stream": {
		"list": "/accounts/{account_id}/stream",
		"get":  "/accounts/{account_id}/stream/{identifier}",
	},
	"cloudflare_stream_audio_track": {
		"list": "",
		"get":  "/accounts/{account_id}/stream/{identifier}/audio",
	},
	"cloudflare_stream_key": {
		"list": "",
		"get":  "/accounts/{account_id}/stream/keys",
	},
	"cloudflare_stream_live_input": {
		"list": "/accounts/{account_id}/stream/live_inputs",
		"get":  "/accounts/{account_id}/stream/live_inputs/{live_input_identifier}",
	},
	"cloudflare_stream_watermark": {
		"list": "/accounts/{account_id}/stream/watermarks",
		"get":  "/accounts/{account_id}/stream/watermarks/{identifier}",
	},
	"cloudflare_stream_webhook": {
		"list": "",
		"get":  "/accounts/{account_id}/stream/webhook",
	},
	"cloudflare_stream_caption_language": {
		"list": "",
		"get":  "/accounts/{account_id}/stream/{identifier}/captions/{language}",
	},
	"cloudflare_stream_download": {
		"list": "",
		"get":  "/accounts/{account_id}/stream/{identifier}/downloads",
	},
	"cloudflare_notification_policy_webhooks": {
		"list": "/accounts/{account_id}/alerting/v3/destinations/webhooks",
		"get":  "/accounts/{account_id}/alerting/v3/destinations/webhooks/{webhook_id}",
	},
	"cloudflare_notification_policy": {
		"list": "/accounts/{account_id}/alerting/v3/policies",
		"get":  "/accounts/{account_id}/alerting/v3/policies/{policy_id}",
	},
	"cloudflare_d1_database": {
		"list": "/accounts/{account_id}/d1/database",
		"get":  "/accounts/{account_id}/d1/database/{database_id}",
	},
	"cloudflare_r2_bucket": {
		"list": "/accounts/{account_id}/r2/buckets",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}",
	},
	"cloudflare_r2_bucket_lifecycle": {
		"list": "",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/lifecycle",
	},
	"cloudflare_r2_bucket_cors": {
		"list": "",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/cors",
	},
	"cloudflare_r2_custom_domain": {
		"list": "/accounts/{account_id}/r2/buckets/{bucket_name}/domains/custom",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/domains/custom/{domain}",
	},
	"cloudflare_r2_managed_domain": {
		"list": "/accounts/{account_id}/r2/buckets/{bucket_name}/domains/managed",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/domains/managed",
	},
	"cloudflare_r2_bucket_event_notification": {
		"list": "",
		"get":  "/accounts/{account_id}/event_notifications/r2/{bucket_name}/configuration",
	},
	"cloudflare_r2_bucket_lock": {
		"list": "",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/lock",
	},
	"cloudflare_r2_bucket_sippy": {
		"list": "",
		"get":  "/accounts/{account_id}/r2/buckets/{bucket_name}/sippy",
	},
	"cloudflare_workers_for_platforms_dispatch_namespace": {
		"list": "/accounts/{account_id}/workers/dispatch/namespaces",
		"get":  "/accounts/{account_id}/workers/dispatch/namespaces/{dispatch_namespace}",
	},
	"cloudflare_workers_secret": {
		"list": "/accounts/{account_id}/workers/dispatch/namespaces/{dispatch_namespace}/scripts/{script_name}/secrets",
		"get":  "/accounts/{account_id}/workers/dispatch/namespaces/{dispatch_namespace}/scripts/{script_name}/secrets/{secret_name}",
	},
	"cloudflare_zero_trust_dex_test": {
		"list": "/accounts/{account_id}/devices/dex_tests",
		"get":  "/accounts/{account_id}/devices/dex_tests/{dex_test_id}",
	},
	"cloudflare_zero_trust_device_managed_networks": {
		"list": "/accounts/{account_id}/devices/networks",
		"get":  "/accounts/{account_id}/devices/networks/{network_id}",
	},
	"cloudflare_zero_trust_device_default_profile": {
		"list": "",
		"get":  "/accounts/{account_id}/devices/policy",
	},
	"cloudflare_zero_trust_device_default_profile_local_domain_fallback": {
		"list": "",
		"get":  "/accounts/{account_id}/devices/policy/fallback_domains",
	},
	"cloudflare_zero_trust_device_default_profile_certificates": {
		"list": "",
		"get":  "/zones/{zone_id}/devices/policy/certificates",
	},
	"cloudflare_zero_trust_device_custom_profile": {
		"list": "/accounts/{account_id}/devices/policies",
		"get":  "/accounts/{account_id}/devices/policy/{policy_id}",
	},
	"cloudflare_zero_trust_device_custom_profile_local_domain_fallback": {
		"list": "",
		"get":  "/accounts/{account_id}/devices/policy/{policy_id}/fallback_domains",
	},
	"cloudflare_zero_trust_device_posture_rule": {
		"list": "/accounts/{account_id}/devices/posture",
		"get":  "/accounts/{account_id}/devices/posture/{rule_id}",
	},
	"cloudflare_zero_trust_device_posture_integration": {
		"list": "/accounts/{account_id}/devices/posture/integration",
		"get":  "/accounts/{account_id}/devices/posture/integration/{integration_id}",
	},
	"cloudflare_zero_trust_access_identity_provider": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/identity_providers",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/identity_providers/{identity_provider_id}",
	},
	"cloudflare_zero_trust_organization": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/organizations",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/organizations",
	},
	"cloudflare_zero_trust_access_infrastructure_target": {
		"list": "/accounts/{account_id}/infrastructure/targets",
		"get":  "/accounts/{account_id}/infrastructure/targets/{target_id}",
	},
	"cloudflare_zero_trust_access_application": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/apps",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/apps/{app_id}",
	},
	"cloudflare_zero_trust_access_short_lived_certificate": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/apps/ca",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/apps/{app_id}/ca",
	},
	"cloudflare_zero_trust_access_mtls_certificate": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/certificates",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/certificates/{certificate_id}",
	},
	"cloudflare_zero_trust_access_mtls_hostname_settings": {
		"list": "",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/certificates/settings",
	},
	"cloudflare_zero_trust_access_group": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/groups",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/groups/{group_id}",
	},
	"cloudflare_zero_trust_access_service_token": {
		"list": "/{accounts_or_zones}/{account_or_zone_id}/access/service_tokens",
		"get":  "/{accounts_or_zones}/{account_or_zone_id}/access/service_tokens/{service_token_id}",
	},
	"cloudflare_zero_trust_access_key_configuration": {
		"list": "",
		"get":  "/accounts/{account_id}/access/keys",
	},
	"cloudflare_zero_trust_access_custom_page": {
		"list": "/accounts/{account_id}/access/custom_pages",
		"get":  "/accounts/{account_id}/access/custom_pages/{custom_page_id}",
	},
	"cloudflare_zero_trust_access_tag": {
		"list": "/accounts/{account_id}/access/tags",
		"get":  "/accounts/{account_id}/access/tags/{tag_name}",
	},
	"cloudflare_zero_trust_access_policy": {
		"list": "/accounts/{account_id}/access/policies",
		"get":  "/accounts/{account_id}/access/policies/{policy_id}",
	},
	"cloudflare_zero_trust_tunnel_cloudflared": {
		"list": "/accounts/{account_id}/cfd_tunnel",
		"get":  "/accounts/{account_id}/cfd_tunnel/{tunnel_id}",
	},
	"cloudflare_zero_trust_tunnel_cloudflared_config": {
		"list": "",
		"get":  "/accounts/{account_id}/cfd_tunnel/{tunnel_id}/configurations",
	},
	"cloudflare_zero_trust_dlp_dataset": {
		"list": "/accounts/{account_id}/dlp/datasets",
		"get":  "/accounts/{account_id}/dlp/datasets/{dataset_id}",
	},
	"cloudflare_zero_trust_dlp_custom_profile": {
		"list": "",
		"get":  "/accounts/{account_id}/dlp/profiles/custom/{profile_id}",
	},
	"cloudflare_zero_trust_dlp_predefined_profile": {
		"list": "",
		"get":  "/accounts/{account_id}/dlp/profiles/predefined/{profile_id}",
	},
	"cloudflare_zero_trust_dlp_entry": {
		"list": "/accounts/{account_id}/dlp/entries",
		"get":  "/accounts/{account_id}/dlp/entries/{entry_id}",
	},
	"cloudflare_zero_trust_gateway_categories": {
		"list": "/accounts/{account_id}/gateway/categories",
		"get":  "/accounts/{account_id}/gateway/categories",
	},
	"cloudflare_zero_trust_gateway_app_types": {
		"list": "/accounts/{account_id}/gateway/app_types",
		"get":  "/accounts/{account_id}/gateway/app_types",
	},
	"cloudflare_zero_trust_gateway_settings": {
		"list": "",
		"get":  "/accounts/{account_id}/gateway/configuration",
	},
	"cloudflare_zero_trust_list": {
		"list": "/accounts/{account_id}/gateway/lists",
		"get":  "/accounts/{account_id}/gateway/lists/{list_id}",
	},
	"cloudflare_zero_trust_dns_location": {
		"list": "/accounts/{account_id}/gateway/locations",
		"get":  "/accounts/{account_id}/gateway/locations/{location_id}",
	},
	"cloudflare_zero_trust_gateway_logging": {
		"list": "",
		"get":  "/accounts/{account_id}/gateway/logging",
	},
	"cloudflare_zero_trust_gateway_proxy_endpoint": {
		"list": "/accounts/{account_id}/gateway/proxy_endpoints",
		"get":  "/accounts/{account_id}/gateway/proxy_endpoints/{proxy_endpoint_id}",
	},
	"cloudflare_zero_trust_gateway_policy": {
		"list": "/accounts/{account_id}/gateway/rules",
		"get":  "/accounts/{account_id}/gateway/rules/{rule_id}",
	},
	"cloudflare_zero_trust_gateway_certificate": {
		"list": "/accounts/{account_id}/gateway/certificates",
		"get":  "/accounts/{account_id}/gateway/certificates/{certificate_id}",
	},
	"cloudflare_zero_trust_tunnel_cloudflared_route": {
		"list": "/accounts/{account_id}/teamnet/routes",
		"get":  "/accounts/{account_id}/teamnet/routes/{route_id}",
	},
	"cloudflare_zero_trust_tunnel_cloudflared_virtual_network": {
		"list": "/accounts/{account_id}/teamnet/virtual_networks",
		"get":  "/accounts/{account_id}/teamnet/virtual_networks/{virtual_network_id}",
	},
	"cloudflare_zero_trust_risk_behavior": {
		"list": "",
		"get":  "/accounts/{account_id}/zt_risk_scoring/behaviors",
	},
	"cloudflare_zero_trust_risk_scoring_integration": {
		"list": "/accounts/{account_id}/zt_risk_scoring/integrations",
		"get":  "/accounts/{account_id}/zt_risk_scoring/integrations/{integration_id}",
	},
	"cloudflare_turnstile_widget": {
		"list": "/accounts/{account_id}/challenges/widgets",
		"get":  "/accounts/{account_id}/challenges/widgets/{sitekey}",
	},
	"cloudflare_hyperdrive_config": {
		"list": "/accounts/{account_id}/hyperdrive/configs",
		"get":  "/accounts/{account_id}/hyperdrive/configs/{hyperdrive_id}",
	},
	"cloudflare_web_analytics_site": {
		"list": "/accounts/{account_id}/rum/site_info/list",
		"get":  "/accounts/{account_id}/rum/site_info/{site_id}",
	},
	"cloudflare_web_analytics_rule": {
		"list": "/accounts/{account_id}/rum/v2/{ruleset_id}/rules",
		"get":  "/accounts/{account_id}/rum/v2/{ruleset_id}/rules",
	},
	"cloudflare_bot_management": {
		"list": "",
		"get":  "/zones/{zone_id}/bot_management",
	},
	"cloudflare_observatory_scheduled_test": {
		"list": "",
		"get":  "/zones/{zone_id}/speed_api/schedule/{url}",
	},
	"cloudflare_hostname_tls_setting": {
		"list": "",
		"get":  "/zones/{zone_id}/hostnames/settings/{setting_id}",
	},
	"cloudflare_snippets": {
		"list": "/zones/{zone_id}/snippets",
		"get":  "/zones/{zone_id}/snippets/{snippet_name}",
	},
	"cloudflare_snippet_rules": {
		"list": "/zones/{zone_id}/snippets/snippet_rules",
		"get":  "/zones/{zone_id}/snippets/snippet_rules",
	},
	"cloudflare_calls_sfu_app": {
		"list": "/accounts/{account_id}/calls/apps",
		"get":  "/accounts/{account_id}/calls/apps/{app_id}",
	},
	"cloudflare_calls_turn_app": {
		"list": "/accounts/{account_id}/calls/turn_keys",
		"get":  "/accounts/{account_id}/calls/turn_keys/{key_id}",
	},
	"cloudflare_cloudforce_one_request": {
		"list": "",
		"get":  "",
	},
	"cloudflare_cloudforce_one_request_message": {
		"list": "",
		"get":  "",
	},
	"cloudflare_cloudforce_one_request_priority": {
		"list": "",
		"get":  "/accounts/{account_identifier}/cloudforce-one/requests/priority/{priority_identifer}",
	},
	"cloudflare_cloudforce_one_request_asset": {
		"list": "",
		"get":  "/accounts/{account_identifier}/cloudforce-one/requests/{request_identifier}/asset/{asset_identifer}",
	},
	"cloudflare_leaked_credential_check": {
		"list": "",
		"get":  "/zones/{zone_id}/leaked-credential-checks",
	},
	"cloudflare_leaked_credential_check_rule": {
		"list": "/zones/{zone_id}/leaked-credential-checks/detections",
		"get":  "/zones/{zone_id}/leaked-credential-checks/detections",
	},
	"cloudflare_content_scanning": {
		"list": "",
		"get":  "",
	},
	"cloudflare_content_scanning_expression": {
		"list": "/zones/{zone_id}/content-upload-scan/payloads",
		"get":  "/zones/{zone_id}/content-upload-scan/payloads",
	},
}
